// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/gate-way/gate-way.proto

package gateway

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GateWay service

func NewGateWayEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GateWay service

type GateWayService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (GateWay_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GateWay_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (GateWay_BidiStreamService, error)
}

type gateWayService struct {
	c    client.Client
	name string
}

func NewGateWayService(name string, c client.Client) GateWayService {
	return &gateWayService{
		c:    c,
		name: name,
	}
}

func (c *gateWayService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "GateWay.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateWayService) ClientStream(ctx context.Context, opts ...client.CallOption) (GateWay_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "GateWay.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gateWayServiceClientStream{stream}, nil
}

type GateWay_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type gateWayServiceClientStream struct {
	stream client.Stream
}

func (x *gateWayServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gateWayServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *gateWayService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (GateWay_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "GateWay.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &gateWayServiceServerStream{stream}, nil
}

type GateWay_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type gateWayServiceServerStream struct {
	stream client.Stream
}

func (x *gateWayServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gateWayServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gateWayService) BidiStream(ctx context.Context, opts ...client.CallOption) (GateWay_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "GateWay.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &gateWayServiceBidiStream{stream}, nil
}

type GateWay_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type gateWayServiceBidiStream struct {
	stream client.Stream
}

func (x *gateWayServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *gateWayServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *gateWayServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GateWay service

type GateWayHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, GateWay_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, GateWay_ServerStreamStream) error
	BidiStream(context.Context, GateWay_BidiStreamStream) error
}

func RegisterGateWayHandler(s server.Server, hdlr GateWayHandler, opts ...server.HandlerOption) error {
	type gateWay interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type GateWay struct {
		gateWay
	}
	h := &gateWayHandler{hdlr}
	return s.Handle(s.NewHandler(&GateWay{h}, opts...))
}

type gateWayHandler struct {
	GateWayHandler
}

func (h *gateWayHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.GateWayHandler.Call(ctx, in, out)
}

func (h *gateWayHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.GateWayHandler.ClientStream(ctx, &gateWayClientStreamStream{stream})
}

type GateWay_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type gateWayClientStreamStream struct {
	stream server.Stream
}

func (x *gateWayClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *gateWayHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.GateWayHandler.ServerStream(ctx, m, &gateWayServerStreamStream{stream})
}

type GateWay_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type gateWayServerStreamStream struct {
	stream server.Stream
}

func (x *gateWayServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *gateWayHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.GateWayHandler.BidiStream(ctx, &gateWayBidiStreamStream{stream})
}

type GateWay_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type gateWayBidiStreamStream struct {
	stream server.Stream
}

func (x *gateWayBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *gateWayBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *gateWayBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *gateWayBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *gateWayBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *gateWayBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
